name: Docker Image CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'setup.py'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get Flowiz version
      id: version
      run: |
        export FLOWIZ_VERSION=$(python setup.py --version)
        echo "::set-output name=ver::${FLOWIZ_VERSION}"
        
    - name: Build and push
      uses: docker/build-push-action@v2.10.0
      with:
        push: true
        tags: georgegach/flowiz:latest,georgegach/flowiz:${{ steps.version.outputs.ver }}
        secrets: |
          GIT_AUTH_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}
